### ISSUE TITLE
Unmanaged test instances should observe CDI events

### ISSUE THREAD

**Issue by ikysil** [cdi-unit/cdi-unit#288]
- [ ] JUnit 4 Runner - see #309 
- [ ] JUnit 4 Rule - see #309 
- [ ] TestNG Runner - see #309 
- [ ] TestNG Listener - see #309 
- [x] JUnit 5 Top-level test - see #287 
- [ ] JUnit 5 Nested test - see #309

**Comment by ikysil** [comment]
JUnit 5 behavior confirmed in https://github.com/cdi-unit/cdi-unit/pull/287

**Comment by ikysil** [comment]
JUnit 5 behavior for nested classes confirmed in https://github.com/cdi-unit/cdi-unit/pull/288
