### ISSUE TITLE
Uniform support for PER_CLASS isolation

### ISSUE THREAD

**Issue by ikysil** [cdi-unit/cdi-unit#289]
- [x] JUnit 4 Runner - see #300
- [x] JUnit 4 Rule - see #300
- [x] TestNG Runner - see #302
- [x] TestNG Listener - see #302
- [x] JUnit 5 Top-level test - see #299
- [x] JUnit 5 Nested test - see #299
